add decorators to class for PR
supreeti/OPPS-Library-Management-System pull request #2
Opened 2023-09-01 16:29 UTC by supreeti

Add namables

2023-09-01 17:13 UTC, fobadara reviewed
Hi @supreeti, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

![INVALID](https://user-images.githubusercontent.com/62938735/260207325-5d147c70-ef69-4196-9c4b-9784dc2ab80a.gif)


## Invalid Code Review Request

You have submitted a project, whose linters are not properly set up. I cant see the all-green pass icon in your PR.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-09-01 18:52 UTC, mikethreels requested changes
Hi Supreeti, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- good job adding the decorator classes

## Required Changes ♻️
- [ ] the link to the MIT license in the readme file is not working as expected, please make sure it works as shown in the template provided by Microverse.
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-01 18:57 UTC, mikethreels requested changes
Hi Supreeti, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- good job adding the decorator classes

## Required Changes ♻️
- [ ] the link to the MIT license in the readme file is not working as expected, please make sure it works as shown in the template provided by Microverse.
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-01 18:57 UTC, mikethreels commented on person.rb
>  class Person
- [ ] the person class should inherit from the nameable class and should have a method correct name.

2023-09-01 19:26 UTC, mikethreels requested changes
Hi Supreeti, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- good job updating the readme file.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-01 19:26 UTC, mikethreels commented on person.rb
>  class Person
- [ ] As mentioned in the previous review, please make sure the person class inherits from the nameable class and has a method called correct name.

2023-09-02 04:18 UTC, tufoinnkuo10 requested changes
Hi @supreeti 

There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight
✅ You used the correct Gitflow
✅ Descriptive pull request message
✅ linter error checks validated

Required Changes ♻️
Check the comments under the review

![tufoin](https://media.giphy.com/media/m3864rBwwBTKMAbpn3/giphy.gif)

Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2023-09-02 04:18 UTC, tufoinnkuo10 commented on person.rb
> +  def initialize(name: 'Unknown', age: nil, parent_permission: true)
- [ ] Great job so far making some of the changes, ie Person class inherits from Nameable class. Please, like the previous reviewer also clearly noted, the person class should have a method `correct_name`. Note that this method is needed by your decorators to work well. eg
```ruby
def correct_name
       name
    end
```

2023-09-02 10:04 UTC, KDlamini approved these changes
### Hi @supreeti 🙋‍♀️,  

Excellent work! 💯 
You have done a great job implementing all the required changes. 🎊 🥳 
Your feature is complete! There is nothing else to say other than... it's time to merge it. :shipit: 
Congratulations!!!

## HIGHLIGHTS 🌟 

✔️ Professional PR title and description
✔️ The `Namable` class has a method 'correct_name' raising an error.
✔️ The `Person` class inherits from `Nameable` class. It also has a method `correct_name`
✔️ The decorator classes inherit from `Nameable` class

# Status: Approved ✔️ 


Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @KDlamini  in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-02 10:04 UTC, KDlamini commented on person.rb
[OPTIONAL] There are a couple of errors with testing your decorators. Kindly look into it to make sure that everything works as expected. This is only optional because it was not mentioned in the previous reviews but it is very crucial for this milestone.

1. Kindly use the correct path to the required files. The `person.rb` file is in the root directory therefore the paths should start with `./` instead of `../`.

![image](https://github.com/supreeti/OPPS-Library-Management-System/assets/38088818/d595e02b-13df-434f-8446-d1a9faf89bc7)

2. The parameters for the `initialize` method for the Person class are not set up correctly resulting in an `ArgumentError` (wrong number of arguments).

![image](https://github.com/supreeti/OPPS-Library-Management-System/assets/38088818/7f5e1803-5ef7-4116-a624-4b5cbb06cb3f)

3. The `correct_name` method throws the error from the `Nameable` class. This suggests that your application is not working as expected, kindly look into it.

![image](https://github.com/supreeti/OPPS-Library-Management-System/assets/38088818/981b07e6-55d3-4674-8fcc-bfcc3485f3da)

2023-09-02 10:17 UTC, supreeti commented on person.rb
ok. I make sure to implement these changes.

2023-09-02 10:17 UTC, merged